#1.项目启动的端口
#server.port = 8080


#jdbc.driver=com.mysql.cj.jdbc.Driver
#jdbc.driver=com.mysql.jdbc.Driver
#jdbc.url=jdbc:mysql://127.0.0.1:3306/myspider?useUnicode=true&characterEncoding=utf-8&useSSL=false
#jdbc.username=root
#jdbc.password=root


spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
  #静态文件配置
  resources:
    static-locations: classpath:/static,classpath:/META-INF/resources,classpath:/templates/
  #jdbc配置
  datasource:
    url: jdbc:mysql://localhost:3306/myspider?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    #url: jdbc:mysql://localhost:3306/dev_myspider?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  #solr配置
  data:
    solr:
      host:http://127.0.0.1:8983/solr/spider
#mybatis配置
mybatis:
  #映射文件路径
  mapper-locations: classpath:mapping/*.xml
  #模型所在的包名
  type-aliases-package: com.java.spider.entity
